// Young Life Sacramento County — School Data
// Source: CA Department of Education 2022-23, US Census ACS estimates
// Coordinates verified against official school addresses

const YL_SCHOOLS = [

  // ── EXISTING YL LOCATIONS ──────────────────────────────────────────────────

  {
    id: 1,
    name: "Natomas High School",
    shortName: "Natomas HS",
    type: "HS",
    status: "existing",
    lat: 38.6541,
    lng: -121.4712,
    district: "Natomas Unified School District",
    grades: "9–12",
    address: "3301 Fong Ranch Road, Sacramento, CA 95834",
    enrollment: 2204,
    frpm: 42,
    attendance: 94,
    demographics: { hispanic: 38, asian: 22, black: 14, white: 16, other: 10 },
    testScores: { ela: 38, math: 26 },
    englishLearners: 18,
    specialEd: 11,
    medianIncome: 71000
  },

  {
    id: 2,
    name: "Folsom High School",
    shortName: "Folsom HS",
    type: "HS",
    status: "existing",
    lat: 38.6463,
    lng: -121.1630,
    district: "Folsom Cordova Unified School District",
    grades: "9–12",
    address: "1999 Prairie City Road, Folsom, CA 95630",
    enrollment: 2547,
    frpm: 14,
    attendance: 96,
    demographics: { hispanic: 16, asian: 16, black: 4, white: 54, other: 10 },
    testScores: { ela: 62, math: 52 },
    englishLearners: 5,
    specialEd: 10,
    medianIncome: 112000
  },

  {
    id: 3,
    name: "California State University, Sacramento",
    shortName: "CSU Sacramento",
    type: "College",
    status: "existing",
    lat: 38.5598,
    lng: -121.4241,
    district: "California State University System",
    grades: "College",
    address: "6000 J Street, Sacramento, CA 95819",
    enrollment: 31000,
    frpm: null,
    attendance: null,
    demographics: { hispanic: 28, asian: 22, black: 8, white: 28, other: 14 },
    testScores: { ela: null, math: null },
    englishLearners: null,
    specialEd: null,
    medianIncome: 55000
  },

  {
    id: 4,
    name: "John F. Kennedy High School",
    shortName: "Kennedy HS",
    type: "HS",
    status: "existing",
    lat: 38.5032,
    lng: -121.5345,
    district: "Sacramento City Unified School District",
    grades: "9–12",
    address: "6715 Gloria Drive, Sacramento, CA 95831",
    enrollment: 1687,
    frpm: 72,
    attendance: 91,
    demographics: { hispanic: 48, asian: 12, black: 24, white: 8, other: 8 },
    testScores: { ela: 28, math: 15 },
    englishLearners: 24,
    specialEd: 12,
    medianIncome: 42000
  },

  {
    id: 5,
    name: "Laguna Creek High School",
    shortName: "Laguna Creek HS",
    type: "HS",
    status: "existing",
    lat: 38.4327,
    lng: -121.4394,
    district: "Elk Grove Unified School District",
    grades: "9–12",
    address: "9050 Vicino Drive, Elk Grove, CA 95758",
    enrollment: 2078,
    frpm: 35,
    attendance: 94,
    demographics: { hispanic: 30, asian: 22, black: 12, white: 28, other: 8 },
    testScores: { ela: 46, math: 34 },
    englishLearners: 12,
    specialEd: 10,
    medianIncome: 78000
  },

  {
    id: 6,
    name: "Elk Grove High School",
    shortName: "Elk Grove HS",
    type: "HS",
    status: "existing",
    lat: 38.4088,
    lng: -121.3716,
    district: "Elk Grove Unified School District",
    grades: "9–12",
    address: "9800 Elk Grove-Florin Road, Elk Grove, CA 95624",
    enrollment: 2712,
    frpm: 28,
    attendance: 95,
    demographics: { hispanic: 24, asian: 28, black: 14, white: 24, other: 10 },
    testScores: { ela: 50, math: 38 },
    englishLearners: 10,
    specialEd: 10,
    medianIncome: 82000
  },

  {
    id: 7,
    name: "Katherine L. Albiani Middle School",
    shortName: "Albiani MS",
    type: "MS",
    status: "existing",
    lat: 38.4200,
    lng: -121.3630,
    district: "Elk Grove Unified School District",
    grades: "6–8",
    address: "9140 Bradshaw Road, Elk Grove, CA 95624",
    enrollment: 752,
    frpm: 25,
    attendance: 95,
    demographics: { hispanic: 22, asian: 30, black: 12, white: 26, other: 10 },
    testScores: { ela: 48, math: 40 },
    englishLearners: 8,
    specialEd: 9,
    medianIncome: 88000
  },

  {
    id: 8,
    name: "Sacramento County Youth Detention Facility",
    shortName: "Youth Detention",
    type: "Special",
    status: "existing",
    lat: 38.5665,
    lng: -121.3296,
    district: "Sacramento County Office of Education",
    grades: "K–12",
    address: "4136 Branch Center Road, Sacramento, CA 95827",
    enrollment: 120,
    frpm: 100,
    attendance: null,
    demographics: { hispanic: 45, asian: 5, black: 35, white: 10, other: 5 },
    testScores: { ela: null, math: null },
    englishLearners: 20,
    specialEd: 25,
    medianIncome: null
  },

  // ── TARGET SCHOOLS ─────────────────────────────────────────────────────────

  {
    id: 9,
    name: "Encina High School",
    shortName: "Encina HS",
    type: "HS",
    status: "target",
    lat: 38.6052,
    lng: -121.3928,
    district: "San Juan Unified School District",
    grades: "9–12",
    address: "1400 Bell Street, Sacramento, CA 95825",
    enrollment: 1650,
    frpm: 48,
    attendance: 92,
    demographics: { hispanic: 38, asian: 16, black: 20, white: 18, other: 8 },
    testScores: { ela: 34, math: 22 },
    englishLearners: 18,
    specialEd: 12,
    medianIncome: 58000
  },

  {
    id: 10,
    name: "Sacramento High School",
    shortName: "Sacramento HS",
    type: "HS",
    status: "target",
    lat: 38.5507,
    lng: -121.4553,
    district: "Sacramento City Unified School District",
    grades: "9–12",
    address: "2315 34th Street, Sacramento, CA 95817",
    enrollment: 1248,
    frpm: 76,
    attendance: 90,
    demographics: { hispanic: 52, asian: 8, black: 26, white: 6, other: 8 },
    testScores: { ela: 22, math: 12 },
    englishLearners: 28,
    specialEd: 13,
    medianIncome: 38000
  },

  {
    id: 11,
    name: "California Middle School",
    shortName: "California MS",
    type: "MS",
    status: "target",
    lat: 38.5490,
    lng: -121.4750,
    district: "Sacramento City Unified School District",
    grades: "6–8",
    address: "1600 Vallejo Way, Sacramento, CA 95818",
    enrollment: 824,
    frpm: 70,
    attendance: 91,
    demographics: { hispanic: 50, asian: 10, black: 22, white: 10, other: 8 },
    testScores: { ela: 26, math: 18 },
    englishLearners: 25,
    specialEd: 12,
    medianIncome: 40000
  },

  {
    id: 12,
    name: "C.K. McClatchy High School",
    shortName: "McClatchy HS",
    type: "HS",
    status: "target",
    lat: 38.5507,
    lng: -121.4747,
    district: "Sacramento City Unified School District",
    grades: "9–12",
    address: "3066 Freeport Boulevard, Sacramento, CA 95818",
    enrollment: 1754,
    frpm: 68,
    attendance: 91,
    demographics: { hispanic: 46, asian: 10, black: 24, white: 12, other: 8 },
    testScores: { ela: 30, math: 18 },
    englishLearners: 22,
    specialEd: 12,
    medianIncome: 44000
  },

  {
    id: 13,
    name: "Albert Einstein Middle School",
    shortName: "Einstein MS",
    type: "MS",
    status: "target",
    lat: 38.5580,
    lng: -121.3610,
    district: "Sacramento City Unified School District",
    grades: "6–8",
    address: "9325 Mirandy Drive, Sacramento, CA 95826",
    enrollment: 714,
    frpm: 65,
    attendance: 92,
    demographics: { hispanic: 42, asian: 14, black: 22, white: 14, other: 8 },
    testScores: { ela: 32, math: 22 },
    englishLearners: 20,
    specialEd: 11,
    medianIncome: 48000
  },

  {
    id: 14,
    name: "Rosemont High School",
    shortName: "Rosemont HS",
    type: "HS",
    status: "target",
    lat: 38.5659,
    lng: -121.3296,
    district: "Sacramento City Unified School District",
    grades: "9–12",
    address: "9594 Kiefer Boulevard, Sacramento, CA 95827",
    enrollment: 1389,
    frpm: 62,
    attendance: 92,
    demographics: { hispanic: 44, asian: 16, black: 20, white: 12, other: 8 },
    testScores: { ela: 34, math: 22 },
    englishLearners: 20,
    specialEd: 11,
    medianIncome: 50000
  },

  {
    id: 15,
    name: "Monterey Trail High School",
    shortName: "Monterey Trail HS",
    type: "HS",
    status: "target",
    lat: 38.4501,
    lng: -121.3990,
    district: "Elk Grove Unified School District",
    grades: "9–12",
    address: "8661 Power Inn Road, Elk Grove, CA 95624",
    enrollment: 2514,
    frpm: 38,
    attendance: 94,
    demographics: { hispanic: 30, asian: 20, black: 16, white: 26, other: 8 },
    testScores: { ela: 44, math: 32 },
    englishLearners: 12,
    specialEd: 10,
    medianIncome: 74000
  },

  {
    id: 16,
    name: "Sheldon High School",
    shortName: "Sheldon HS",
    type: "HS",
    status: "target",
    lat: 38.4553,
    lng: -121.3481,
    district: "Elk Grove Unified School District",
    grades: "9–12",
    address: "8333 Kingsbridge Drive, Sacramento, CA 95829",
    enrollment: 2187,
    frpm: 30,
    attendance: 95,
    demographics: { hispanic: 26, asian: 24, black: 12, white: 30, other: 8 },
    testScores: { ela: 48, math: 36 },
    englishLearners: 10,
    specialEd: 10,
    medianIncome: 84000
  },

  {
    id: 17,
    name: "Harriet G. Eddy Middle School",
    shortName: "Harriet Eddy MS",
    type: "MS",
    status: "target",
    lat: 38.4400,
    lng: -121.4300,
    district: "Elk Grove Unified School District",
    grades: "6–8",
    address: "9329 Soaring Oaks Drive, Elk Grove, CA 95758",
    enrollment: 847,
    frpm: 35,
    attendance: 94,
    demographics: { hispanic: 30, asian: 20, black: 14, white: 28, other: 8 },
    testScores: { ela: 44, math: 36 },
    englishLearners: 12,
    specialEd: 10,
    medianIncome: 76000
  },

  {
    id: 18,
    name: "Pleasant Grove High School",
    shortName: "Pleasant Grove HS",
    type: "HS",
    status: "target",
    lat: 38.4383,
    lng: -121.3819,
    district: "Elk Grove Unified School District",
    grades: "9–12",
    address: "9531 Bond Road, Elk Grove, CA 95624",
    enrollment: 2012,
    frpm: 34,
    attendance: 95,
    demographics: { hispanic: 25, asian: 26, black: 12, white: 28, other: 9 },
    testScores: { ela: 46, math: 34 },
    englishLearners: 10,
    specialEd: 10,
    medianIncome: 86000
  },

  {
    id: 19,
    name: "Joseph Kerr Middle School",
    shortName: "Joseph Kerr MS",
    type: "MS",
    status: "target",
    lat: 38.4100,
    lng: -121.3740,
    district: "Elk Grove Unified School District",
    grades: "6–8",
    address: "8865 Elk Grove Boulevard, Elk Grove, CA 95624",
    enrollment: 824,
    frpm: 32,
    attendance: 95,
    demographics: { hispanic: 24, asian: 26, black: 12, white: 28, other: 10 },
    testScores: { ela: 46, math: 38 },
    englishLearners: 10,
    specialEd: 9,
    medianIncome: 84000
  }

];

// CA statewide averages (CAASPP 2022-23)
const STATE_AVERAGES = { ela: 47, math: 35 };
