// Young Life Sacramento County — School Data
// Source: CA Dept. of Education SARC 2023-24, CAASPP 2023-24, EdData.org, CA School Dashboard
// All academic figures reflect 2023-24 school year unless noted
//
// progress values: "active" | "exploring" | "leader_identified" | "club_launched"
// notes: short context blurb shown to donors — edit here or via Google Sheets
// photoUrl: optional image URL shown at top of sidebar

const YL_SCHOOLS = [

  // ── EXISTING YL LOCATIONS ──────────────────────────────────────────────────

  {
    id: 1,
    name: "Natomas High School",
    shortName: "Natomas HS",
    type: "HS", status: "existing",
    progress: "active",
    notes: "",
    photoUrl: "",
    lat: 38.6541, lng: -121.4712,
    district: "Natomas Unified School District",
    grades: "9–12",
    address: "3301 Fong Ranch Road, Sacramento, CA 95834",
    enrollment: 1157,
    frpm: 78,
    attendance: 91,
    chronicAbsenteeism: 32,
    suspensionRate: null,
    graduationRate: 92,
    collegeCareerReady: null,
    demographics: { hispanic: 52, asian: 11, black: 21, white: 8, filipino: 1, twoOrMore: 5, other: 2 },
    testScores: { ela: 40, math: 8 },
    englishLearners: 13,
    specialEd: 12,
    medianIncome: 71000
  },

  {
    id: 2,
    name: "Folsom High School",
    shortName: "Folsom HS",
    type: "HS", status: "existing",
    progress: "active",
    notes: "",
    photoUrl: "",
    lat: 38.6463, lng: -121.1630,
    district: "Folsom Cordova Unified School District",
    grades: "9–12",
    address: "1999 Prairie City Road, Folsom, CA 95630",
    enrollment: 2901,
    frpm: 22,
    attendance: 96,
    chronicAbsenteeism: 13,
    suspensionRate: 2.5,
    graduationRate: 97,
    collegeCareerReady: 69,
    demographics: { hispanic: 17, asian: 26, black: 3, white: 42, filipino: 4, twoOrMore: 11, other: 1 },
    testScores: { ela: 80, math: 51 },
    englishLearners: 5,
    specialEd: 9,
    medianIncome: 112000
  },

  {
    id: 3,
    name: "California State University, Sacramento",
    shortName: "CSU Sacramento",
    type: "College", status: "existing",
    progress: "active",
    notes: "",
    photoUrl: "",
    lat: 38.5598, lng: -121.4241,
    district: "California State University System",
    grades: "College",
    address: "6000 J Street, Sacramento, CA 95819",
    enrollment: 31000,
    frpm: null, attendance: null, chronicAbsenteeism: null,
    suspensionRate: null, graduationRate: null, collegeCareerReady: null,
    demographics: { hispanic: 28, asian: 22, black: 8, white: 28, filipino: 3, twoOrMore: 7, other: 4 },
    testScores: { ela: null, math: null },
    englishLearners: null, specialEd: null, medianIncome: 55000
  },

  {
    id: 4,
    name: "John F. Kennedy High School",
    shortName: "Kennedy HS",
    type: "HS", status: "existing",
    progress: "active",
    notes: "",
    photoUrl: "",
    lat: 38.5032, lng: -121.5345,
    district: "Sacramento City Unified School District",
    grades: "9–12",
    address: "6715 Gloria Drive, Sacramento, CA 95831",
    enrollment: 1652,
    frpm: 64,
    attendance: 72,
    chronicAbsenteeism: 27,
    suspensionRate: 6,
    graduationRate: 88,
    collegeCareerReady: null,
    demographics: { hispanic: 35, asian: 25, black: 19, white: 10, filipino: 2, twoOrMore: 8, other: 1 },
    testScores: { ela: 44, math: 20 },
    englishLearners: 15,
    specialEd: 12,
    medianIncome: 42000
  },

  {
    id: 5,
    name: "Laguna Creek High School",
    shortName: "Laguna Creek HS",
    type: "HS", status: "existing",
    progress: "active",
    notes: "",
    photoUrl: "",
    lat: 38.4327, lng: -121.4394,
    district: "Elk Grove Unified School District",
    grades: "9–12",
    address: "9050 Vicino Drive, Elk Grove, CA 95758",
    enrollment: 2142,
    frpm: 43,
    attendance: 94,
    chronicAbsenteeism: null,
    suspensionRate: null,
    graduationRate: 93,
    collegeCareerReady: null,
    demographics: { hispanic: 27, asian: 29, black: 14, white: 17, filipino: 1, twoOrMore: 11, other: 1 },
    testScores: { ela: 51, math: 37 },
    englishLearners: 16,
    specialEd: 10,
    medianIncome: 78000
  },

  {
    id: 6,
    name: "Elk Grove High School",
    shortName: "Elk Grove HS",
    type: "HS", status: "existing",
    progress: "active",
    notes: "",
    photoUrl: "",
    lat: 38.4088, lng: -121.3716,
    district: "Elk Grove Unified School District",
    grades: "9–12",
    address: "9800 Elk Grove-Florin Road, Elk Grove, CA 95624",
    enrollment: 1684,
    frpm: 37,
    attendance: 95,
    chronicAbsenteeism: null,
    suspensionRate: null,
    graduationRate: 92,
    collegeCareerReady: null,
    demographics: { hispanic: 27, asian: 17, black: 7, white: 36, filipino: 2, twoOrMore: 10, other: 1 },
    testScores: { ela: 61, math: 32 },
    englishLearners: 10,
    specialEd: 10,
    medianIncome: 82000
  },

  {
    id: 7,
    name: "Katherine L. Albiani Middle School",
    shortName: "Albiani MS",
    type: "MS", status: "existing",
    progress: "active",
    notes: "",
    photoUrl: "",
    lat: 38.4200, lng: -121.3630,
    district: "Elk Grove Unified School District",
    grades: "6–8",
    address: "9140 Bradshaw Road, Elk Grove, CA 95624",
    enrollment: 1391,
    frpm: 31,
    attendance: 95,
    chronicAbsenteeism: null,
    suspensionRate: null,
    graduationRate: null,
    collegeCareerReady: null,
    demographics: { hispanic: 20, asian: 35, black: 4, white: 27, filipino: 1, twoOrMore: 13, other: 0 },
    testScores: { ela: 67, math: 56 },
    englishLearners: 8,
    specialEd: 9,
    medianIncome: 88000
  },

  {
    id: 8,
    name: "Sacramento County Youth Detention Facility",
    shortName: "Youth Detention",
    type: "Special", status: "existing",
    progress: "active",
    notes: "",
    photoUrl: "",
    lat: 38.5665, lng: -121.3296,
    district: "Sacramento County Office of Education",
    grades: "K–12",
    address: "4136 Branch Center Road, Sacramento, CA 95827",
    enrollment: null,
    frpm: 100,
    attendance: null, chronicAbsenteeism: null,
    suspensionRate: null, graduationRate: null, collegeCareerReady: null,
    demographics: { hispanic: 45, asian: 3, black: 38, white: 8, filipino: 1, twoOrMore: 3, other: 2 },
    testScores: { ela: null, math: null },
    englishLearners: 20, specialEd: 30, medianIncome: null
  },

  // ── TARGET SCHOOLS ─────────────────────────────────────────────────────────

  {
    id: 9,
    name: "Encina Preparatory High School",
    shortName: "Encina Prep HS",
    type: "HS", status: "target",
    progress: "not_started",
    notes: "",
    photoUrl: "",
    lat: 38.6052, lng: -121.3928,
    district: "San Juan Unified School District",
    grades: "9–12",
    address: "1400 Bell Street, Sacramento, CA 95825",
    enrollment: 628,
    frpm: 77,
    attendance: 92,
    chronicAbsenteeism: null,
    suspensionRate: null,
    graduationRate: 77,
    collegeCareerReady: null,
    demographics: { hispanic: 31, asian: 27, black: 17, white: 18, filipino: 1, twoOrMore: 4, other: 2 },
    testScores: { ela: 10, math: 1 },
    englishLearners: 16,
    specialEd: 12,
    medianIncome: 58000
  },

  {
    id: 10,
    name: "Sacramento Charter High School",
    shortName: "Sacramento HS",
    type: "HS", status: "target",
    progress: "not_started",
    notes: "",
    photoUrl: "",
    lat: 38.5507, lng: -121.4553,
    district: "Sacramento City Unified School District",
    grades: "9–12",
    address: "2315 34th Street, Sacramento, CA 95817",
    enrollment: 380,
    frpm: 73,
    attendance: 90,
    chronicAbsenteeism: null,
    suspensionRate: null,
    graduationRate: 87,
    collegeCareerReady: null,
    demographics: { hispanic: 27, asian: 1, black: 58, white: 2, filipino: 1, twoOrMore: 10, other: 1 },
    testScores: { ela: 65, math: 8 },
    englishLearners: 10,
    specialEd: 13,
    medianIncome: 38000
  },

  {
    id: 11,
    name: "California Middle School",
    shortName: "California MS",
    type: "MS", status: "target",
    progress: "not_started",
    notes: "",
    photoUrl: "",
    lat: 38.5490, lng: -121.4750,
    district: "Sacramento City Unified School District",
    grades: "6–8",
    address: "1600 Vallejo Way, Sacramento, CA 95818",
    enrollment: 753,
    frpm: 69,
    attendance: 91,
    chronicAbsenteeism: 29,
    suspensionRate: 11,
    graduationRate: null,
    collegeCareerReady: null,
    demographics: { hispanic: 47, asian: 9, black: 15, white: 16, filipino: 1, twoOrMore: 10, other: 2 },
    testScores: { ela: 41, math: 33 },
    englishLearners: 12,
    specialEd: 19,
    medianIncome: 40000
  },

  {
    id: 12,
    name: "C.K. McClatchy High School",
    shortName: "McClatchy HS",
    type: "HS", status: "target",
    progress: "not_started",
    notes: "",
    photoUrl: "",
    lat: 38.5507, lng: -121.4747,
    district: "Sacramento City Unified School District",
    grades: "9–12",
    address: "3066 Freeport Boulevard, Sacramento, CA 95818",
    enrollment: 2481,
    frpm: 58,
    attendance: 74,
    chronicAbsenteeism: 27,
    suspensionRate: 6,
    graduationRate: null,
    collegeCareerReady: null,
    demographics: { hispanic: 44, asian: 14, black: 8, white: 23, filipino: 2, twoOrMore: 8, other: 1 },
    testScores: { ela: 46, math: 28 },
    englishLearners: 15,
    specialEd: 12,
    medianIncome: 44000
  },

  {
    id: 13,
    name: "Albert Einstein Middle School",
    shortName: "Einstein MS",
    type: "MS", status: "target",
    progress: "not_started",
    notes: "",
    photoUrl: "",
    lat: 38.5580, lng: -121.3610,
    district: "Sacramento City Unified School District",
    grades: "6–8",
    address: "9325 Mirandy Drive, Sacramento, CA 95826",
    enrollment: 609,
    frpm: 75,
    attendance: 92,
    chronicAbsenteeism: 32,
    suspensionRate: null,
    graduationRate: null,
    collegeCareerReady: null,
    demographics: { hispanic: 41, asian: 8, black: 16, white: 22, filipino: 1, twoOrMore: 10, other: 2 },
    testScores: { ela: 35, math: 19 },
    englishLearners: 15,
    specialEd: 12,
    medianIncome: 48000
  },

  {
    id: 14,
    name: "Rosemont High School",
    shortName: "Rosemont HS",
    type: "HS", status: "target",
    progress: "not_started",
    notes: "",
    photoUrl: "",
    lat: 38.5659, lng: -121.3296,
    district: "Sacramento City Unified School District",
    grades: "9–12",
    address: "9594 Kiefer Boulevard, Sacramento, CA 95827",
    enrollment: 1515,
    frpm: 64,
    attendance: 92,
    chronicAbsenteeism: 32,
    suspensionRate: 6,
    graduationRate: 85,
    collegeCareerReady: null,
    demographics: { hispanic: 36, asian: 10, black: 16, white: 26, filipino: 1, twoOrMore: 10, other: 1 },
    testScores: { ela: 33, math: 12 },
    englishLearners: 15,
    specialEd: 11,
    medianIncome: 50000
  },

  {
    id: 15,
    name: "Monterey Trail High School",
    shortName: "Monterey Trail HS",
    type: "HS", status: "target",
    progress: "not_started",
    notes: "",
    photoUrl: "",
    lat: 38.4501, lng: -121.3990,
    district: "Elk Grove Unified School District",
    grades: "9–12",
    address: "8661 Power Inn Road, Elk Grove, CA 95624",
    enrollment: 2298,
    frpm: 68,
    attendance: 94,
    chronicAbsenteeism: 21,
    suspensionRate: null,
    graduationRate: 93,
    collegeCareerReady: null,
    demographics: { hispanic: 23, asian: 44, black: 17, white: 5, filipino: 3, twoOrMore: 7, other: 1 },
    testScores: { ela: 41, math: 21 },
    englishLearners: 11,
    specialEd: 10,
    medianIncome: 74000
  },

  {
    id: 16,
    name: "Sheldon High School",
    shortName: "Sheldon HS",
    type: "HS", status: "target",
    progress: "not_started",
    notes: "",
    photoUrl: "",
    lat: 38.4553, lng: -121.3481,
    district: "Elk Grove Unified School District",
    grades: "9–12",
    address: "8333 Kingsbridge Drive, Sacramento, CA 95829",
    enrollment: 2415,
    frpm: 50,
    attendance: 95,
    chronicAbsenteeism: null,
    suspensionRate: null,
    graduationRate: 96,
    collegeCareerReady: null,
    demographics: { hispanic: 25, asian: 42, black: 11, white: 10, filipino: 2, twoOrMore: 9, other: 1 },
    testScores: { ela: 54, math: 29 },
    englishLearners: 10,
    specialEd: 10,
    medianIncome: 84000
  },

  {
    id: 17,
    name: "Harriet G. Eddy Middle School",
    shortName: "Harriet Eddy MS",
    type: "MS", status: "target",
    progress: "not_started",
    notes: "",
    photoUrl: "",
    lat: 38.4400, lng: -121.4300,
    district: "Elk Grove Unified School District",
    grades: "6–8",
    address: "9329 Soaring Oaks Drive, Elk Grove, CA 95758",
    enrollment: 1013,
    frpm: 46,
    attendance: 94,
    chronicAbsenteeism: 22,
    suspensionRate: null,
    graduationRate: null,
    collegeCareerReady: null,
    demographics: { hispanic: 31, asian: 22, black: 12, white: 19, filipino: 2, twoOrMore: 14, other: 0 },
    testScores: { ela: 49, math: 32 },
    englishLearners: 12,
    specialEd: 10,
    medianIncome: 76000
  },

  {
    id: 18,
    name: "Pleasant Grove High School",
    shortName: "Pleasant Grove HS",
    type: "HS", status: "existing",
    progress: "active",
    notes: "",
    photoUrl: "",
    lat: 38.4383, lng: -121.3819,
    district: "Elk Grove Unified School District",
    grades: "9–12",
    address: "9531 Bond Road, Elk Grove, CA 95624",
    enrollment: 2512,
    frpm: 27,
    attendance: 95,
    chronicAbsenteeism: null,
    suspensionRate: null,
    graduationRate: 96,
    collegeCareerReady: null,
    demographics: { hispanic: 18, asian: 34, black: 5, white: 31, filipino: 1, twoOrMore: 10, other: 1 },
    testScores: { ela: 73, math: 60 },
    englishLearners: 10,
    specialEd: 10,
    medianIncome: 86000
  },

  {
    id: 19,
    name: "Joseph Kerr Middle School",
    shortName: "Joseph Kerr MS",
    type: "MS", status: "target",
    progress: "not_started",
    notes: "",
    photoUrl: "",
    lat: 38.4100, lng: -121.3740,
    district: "Elk Grove Unified School District",
    grades: "6–8",
    address: "8865 Elk Grove Boulevard, Elk Grove, CA 95624",
    enrollment: 877,
    frpm: 42,
    attendance: 95,
    chronicAbsenteeism: null,
    suspensionRate: null,
    graduationRate: null,
    collegeCareerReady: null,
    demographics: { hispanic: 30, asian: 15, black: 6, white: 35, filipino: 1, twoOrMore: 12, other: 1 },
    testScores: { ela: 58, math: 44 },
    englishLearners: 10,
    specialEd: 9,
    medianIncome: 84000
  }

];

// CA statewide averages (CAASPP 2023-24)
const STATE_AVERAGES = { ela: 47, math: 35 };
